[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "smart-find"
version = "0.1.0"
description = "A smart product search engine with RAG capabilities"
authors = [
    {name = "Author"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai",
    "pandas",
    "tqdm",
    "qdrant-client",
<<<<<<< HEAD
=======
    "chainlit",
>>>>>>> ebeedf8 (initial commit)
    "python-dotenv",
    "numpy",
    "cohere",
    "gradio",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88

[tool.setuptools]
py-modules = [
    "app.feature_extraction_pipeline",
    "app.ingest_pipeline",
    "app.search_agent",
    "app.ui_app",
    "core.llm_utils",
    "core.prompts",
    "core.vector_store",
]
include-package-data = false

[tool.setuptools.packages.find]
exclude = ["data*", "qdrant_storage*"] 